//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBoard.Pages
{
    public partial class Analytics
    {
        protected global::System.Web.UI.WebControls.DropDownList ProjectDropDown;
        protected global::System.Web.UI.WebControls.Label ProjectHealthLabel;
        protected global::System.Web.UI.WebControls.Label ProjectHealthStatusLabel;
        protected global::System.Web.UI.WebControls.Repeater StressMapRepeater;
        protected global::System.Web.UI.WebControls.Panel EmptyStressMapPanel;
        protected global::System.Web.UI.WebControls.HiddenField ChartDataHidden;
    }
}
