//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBoard.Pages {
    public partial class ModuleVoting {
        protected global::System.Web.UI.WebControls.DropDownList ProjectDropDown;
        protected global::System.Web.UI.WebControls.Repeater ModulesRepeater;
        protected global::System.Web.UI.WebControls.Panel EmptyPanel;
        protected global::System.Web.UI.WebControls.Repeater FeedRepeater;
        protected global::System.Web.UI.WebControls.Panel EmptyFeedPanel;
    }
}
